version: '2'
services:
  backup:
    image: postgres:latest
    command: |
      bash -c 'exec pg_dump -h db -p 5432 -U postgres -v -d crisisresponse_development > /backups/`date '+%Y-%m-%d_%H:%M:%S'`.sql'
    links:
      - db
    volumes:
      - './backups:/backups'

  cache:
    image: memcached:latest

  db:
    image: postgres:latest
    expose:
      - 5432

  restore:
    build: containers/restore
    entrypoint: |
      psql -h db -p 5432 -U postgres -v -d crisisresponse_development -f
    links:
      - db
    volumes:
      - '.:/backup'

  web:
    build: .
    image: codeforamerica/crisisresponse
    command: ./bin/serve
    ports:
      - "$PORT:3000"
    links:
      - db
      - cache
    volumes:
      - .:/app
